### PR TITLE
Create React App Integration

### PR DESCRIPTION
**Pull request by jefflau**
* Adds hot module reloading.
* Jest for unit testing.
* Production build with minification
* Restructures JS
* Adds public folder with index.html for CRA webpack configuration
* Uses requires to get images

Can use `npm start` or `truffle serve` to start the server

### CODE REVIEW

**Comment by jefflau** [comment]
Hey Makoto,

Was away this weekend. So i used create react app which has a production webpack build, to do that you need to run `npm run build` and it'll build the frontend app into a `build` folder. we'll probably need to add the contracts in somehow, but i haven't tested out building a production version and deploying.

`truffle serve` will just run `npm start` which is the development version

**Comment by makoto** [comment]
Is the only difference between development and productions are minification? If so I can approve this. We can have more env specific configuration in  different PR

**Comment by jefflau** [comment]
As far as I am aware yes. Yes I think that would be best.

Sent from my iPhone

On Oct 9, 2016, at 9:59 PM, Makoto Inoue <notifications@github.com<mailto:notifications@github.com>> wrote:


Is the only difference between development and productions are minification? If so I can approve this. We can have more env specific configuration in different PR

-

**Comment by makoto** [comment]
Approved. Please merge.

**Pull request merged**
