### PR TITLE
Added NETWORK env variables

### PR DESCRIPTION
**Pull request by jefflau**
This adds two new npm scripts:

`npm run start:testnet` and `npm run start:mainnet` will both set variables under `process.env.NETWORK` which can be accessed within the app.

`npm start` will now have a default `process.env.NETWORK === 'testrpc'`. We can add more if and when we need it for say read only from augur etc...

### CODE REVIEW

**Comment by makoto** [comment]
Can you add the documentation of how you compile , deploy, build, and serve depending on each network somewhere around https://github.com/makoto/blockparty#running-locally so that I can test out whether it works in all the environment ?

**Comment by jefflau** [comment]
It won't deploy to every network. I've only setup the environment variables in a way that will allow you to use the correct network. We'll still need to do some work like we discussed before by creating a `config.js` to alter the address of the node

**Comment by makoto** [comment]
How do I deploy this app? Currently I am uploading files under `build`  into s3 bucket. Can I still use the same method or do I have to deploy to node.js aware paas platform?

**Comment by makoto** [comment]
I was guessing that `NETWORK=testnet node scripts/build.js ` will work but it's blowing up (even when I create `build/contracts` directory. Does it not write concatenated files as outputs?
```
17:54:48-makoto~/work/blockparty (networkVariables)$ NETWORK=testnet node scripts/build.js 
17:55:00-makoto~/work/blockparty (networkVariables)$ node scripts/build.js 
fs.js:951
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir './build/contracts'

```

**Comment by makoto** [comment]
Given that `build` is for separate PR, signed off by @makoto

**Comment by makoto** [comment]
This PR may be now obsolete after https://github.com/makoto/blockparty/pull/34 . Will double check after deploying to mainnet

**Pull request closed without merging**
